# DATA 
datalink: "https://raw.githubusercontent.com/subhadp/Fraud-Detection-in-Financial-Transactions/refs/heads/main/data/raw/Synthetic_Financial_datasets_log.csv"
dataname: Synthetic_Financial_datasets_log
datarawdirectory: data/raw/
datainterimdirectory: data/interim/
dataprocesseddirectory: data/processed/

# MODELS
modelpath: models/model.pkl

# RESULTS
resultsrawpath: results/results_raw.pkl
resultsevaluatedpath: results/results_evaluated.pkl

# VISUALIZATION
figuredirectory: reports/figures/
